
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1354886
	#The name of the modpack
	modpackName = "The Casket of Reveries"
	#The version of the modpack
	modpackVersion = "Ver1.7.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

